
name: Linux

on:
  push:
    branches:    
      - master
  pull_request:
    branches:    
      - master

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ${{ runner.workspace }}/Qt
        key: ${{ runner.os }}-qt

    - name: Install Qt
      if: steps.cache-qt.outputs.cache-hit != 'true'
      uses: jurplel/install-qt-action@v2

    - name: Install Boost
      run: sudo apt-get install libboost-all-dev

    - name: Run CMake
      uses: ashutoshvarma/action-cmake-build@master
