
name: Windows

on:
  push:
    branches:    
      - master
  pull_request:
    branches:    
      - master

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install Qt
      uses: jurplel/install-qt-action@v2

    - name: Install Boost
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install boost-msvc-14.1

    - name: Run CMake
      uses: ashutoshvarma/action-cmake-build@master
